name: "SaluteBridge"
description: "Use your Salute assistent with HomeAssistant"
version: "0.1.8"
slug: "ha-salute-bridge"
webui: "http://[HOST]:[PORT:9124]"
startup: application
boot: auto
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

ports:
  9124/tcp: 9124
ports_description:
  9124/tcp: Management

homeassistant_api: true

options:
  ha_api_url: ""
  ha_api_token: ""
  sd_mqtt_broker: "mqtt-partners.iot.sberdevices.ru"
  sd_mqtt_broker_port: 8883
  sd_mqtt_login: "mqtt-sber-login"
  sd_mqtt_password: "mqtt-sber-password"
  sd_http_api_endpoint: "https://mqtt-partners.iot.sberdevices.ru"
  log_level: INFO
  host: "0.0.0.0"
  port: 9124

schema:
  ha_api_url: str?
  ha_api_token: str?
  sd_mqtt_broker: str
  sd_mqtt_broker_port: int
  sd_mqtt_login: str
  sd_mqtt_password: password
  sd_http_api_endpoint: str?
  log_level: list(NOTSET|DEBUG|INFO|WARNING|ERROR|FATAL)
  host: str
  port: int
