version: '3'
services:
  salute-bridge:
    container_name: salute-bridge
#    image: evgsd/salute-bridge
    build:
      dockerfile: Dockerfile
      args:
        BUILD_FROM: ghcr.io/home-assistant/amd64-base-python:3.12-alpine3.21
    network_mode: host
#    ports:
#      - "9124:9124"
#    expose:
#      - "9124"
    volumes:
      - ./data:/data
    restart: always
    logging:
      options:
        max-size: 10m